image: ghcr.io/cirruslabs/flutter:latest
pipelines:
  branches:
    testing01:
      - step:
          max-time: 120
          size: 2x
          script:
            - flutter pub get
            - flutter analyze
            - flutter build appbundle
