# The name of the workflow
name: first-test

# The event that triggers the workflow
on: [push]

jobs:
  analysis:
    # The name of the job
    name: example
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name:  Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - name: Get Flutter Resources
        run: flutter pub get
      - name: Build App Bundle
        run: flutter build appbundle
      - name: 'Check File Existence'
        uses: thebinaryfelix/check-file-existence-action@1.0.0
        with:
          files: 'app-release.aab'



#      - run: flutter pub get
#      - name: Build .aab
#        run: flutter build appbundle
#        env:
#          SIGNING_KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
#          SIGNING_KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
#          SIGNING_STORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
#      - name: Decode Keystore
#        id: decode_keystore
#        uses: timheuer/base64-to-file@v1.2
#        with:
#          fileName: 'upload-keystore.jks'
#          fileDir: '/home/runner/work/video2audio/video2audio/android/app/keystore/'
#          encodedString: ${{ secrets.KEYSTORE }}
#      - name: 'Check File Existence'
#        uses: thebinaryfelix/check-file-existence-action@1.0.0
#        with:
#          files: 'upload-keystore.jks'
